package calculadora;

import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;

/**
 *
 * @author Brhayan Ramos Gamboa
 */
public class interfazNota extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public interfazNota() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        arrayNotas = new javax.swing.JTextField();
        calcularPromedio = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        imprimirPromedio = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        notaAprobatoria = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Calcular promedio");
        setBackground(new java.awt.Color(255, 204, 0));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        arrayNotas.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N

        calcularPromedio.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        calcularPromedio.setText("Promediar");
        calcularPromedio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calcularPromedioActionPerformed(evt);
            }
        });

        imprimirPromedio.setEditable(false);
        imprimirPromedio.setColumns(20);
        imprimirPromedio.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        imprimirPromedio.setRows(1);
        jScrollPane1.setViewportView(imprimirPromedio);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Resultado");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Ingrese las notas separadas por coma, ejemplo: 0,...,10");

        notaAprobatoria.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        notaAprobatoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "6", "7", "8" }));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Selecciona el valor de la nota aprobatoria:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(calcularPromedio))
                    .addComponent(arrayNotas)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(notaAprobatoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(0, 103, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(arrayNotas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(notaAprobatoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(calcularPromedio)
                .addGap(10, 10, 10))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void calcularPromedioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calcularPromedioActionPerformed

        final Pattern pattern = Pattern.compile("[a-z]");
        final Matcher matcher = pattern.matcher(arrayNotas.getText());
        boolean regex = matcher.find();

        String values[] = arrayNotas.getText().split("\\,");
        int lengthNotas = values.length;
        if (arrayNotas.getText().equals("")) {
            Operaciones.mostrarMensaje("Atención", "No ha agregado ninguna nota", JOptionPane.WARNING_MESSAGE);
        } else if (regex) {
            Operaciones.mostrarMensaje("Error", "Debes ingresar solo números", JOptionPane.ERROR_MESSAGE);
        } else {

            if (lengthNotas < 2) {
                Operaciones.mostrarMensaje("Error", "Debes ingresar al menos 2 notas", JOptionPane.ERROR_MESSAGE);
            } else {

                boolean validarNumero = false;
                float array[] = new float[lengthNotas];
                for (int i = 0; i < lengthNotas; i++) {
                    array[i] = Float.parseFloat(values[i]);
                    if (array[i] < 0 || array[i] > 10) {
                        validarNumero = true;
                    }
                }

                Operaciones limitar = new Operaciones(array);
                float promedio = limitar.calcularPromedio();
                if (validarNumero) {
                    Operaciones.mostrarMensaje("Atención", "Nota fuera de rango, debe ser 0-10", JOptionPane.WARNING_MESSAGE);
                    imprimirPromedio.setText("Proporcione una nota entre 0 - 10");
                } else {
                    imprimirPromedio.setText("Promedio final = " + limitar.limitarDecimal(promedio) + "\n");
                    imprimirPromedio.append(promedio >= Integer.parseInt(notaAprobatoria.getSelectedItem().toString()) ? "Has aprobado el curso :)" : "Debes repetir el curso :(");
                }
            }

        }
    }//GEN-LAST:event_calcularPromedioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(interfazNota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(interfazNota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(interfazNota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(interfazNota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new interfazNota().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private static javax.swing.JTextField arrayNotas;
    private javax.swing.JButton calcularPromedio;
    private javax.swing.JTextArea imprimirPromedio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> notaAprobatoria;
    // End of variables declaration//GEN-END:variables
}
