package calculadora;

import java.util.Arrays;
import java.util.regex.Matcher;
import javax.swing.JOptionPane;
import java.util.regex.Pattern;

/**
 *
 * @author Brhayan Ramos Gamboa
 */
public class interfazInicio extends javax.swing.JFrame {

    /**
     * Creates new form numeros
     */
    public interfazInicio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        realizarOperacion = new javax.swing.JButton();
        input = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        pantallaResultado = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        extra = new javax.swing.JMenu();
        InterfazPromedio = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Calculadora arreglo");
        setBackground(new java.awt.Color(255, 153, 102));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);

        realizarOperacion.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        realizarOperacion.setText("Realizar operaciones");
        realizarOperacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                realizarOperacionActionPerformed(evt);
            }
        });

        input.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N

        pantallaResultado.setEditable(false);
        pantallaResultado.setColumns(20);
        pantallaResultado.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        pantallaResultado.setRows(5);
        jScrollPane1.setViewportView(pantallaResultado);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Ingrese valores separados por comas, ejemplo: 1,2,3,4,5");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Resultados");

        extra.setText("Extra");

        InterfazPromedio.setText("Calcular promedio");
        InterfazPromedio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InterfazPromedioActionPerformed(evt);
            }
        });
        extra.add(InterfazPromedio);

        jMenuBar1.add(extra);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(realizarOperacion))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 467, Short.MAX_VALUE)
                    .addComponent(input)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(input, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(realizarOperacion)
                .addGap(12, 12, 12))
        );

        getAccessibleContext().setAccessibleDescription("Realiza tus operaciones básicas");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void realizarOperacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_realizarOperacionActionPerformed

        final Pattern pattern = Pattern.compile("[a-z]");
        final Matcher matcher = pattern.matcher(input.getText());
        boolean regex = matcher.find();

        if (input.getText().isEmpty()) {
            Operaciones.mostrarMensaje("Atención", "Debe ingresar al menos un valor en el arreglo", JOptionPane.WARNING_MESSAGE);
        } else if (regex) {
            Operaciones.mostrarMensaje("Error", "Debes ingresar solo números", JOptionPane.ERROR_MESSAGE);
        } else {

            String values[] = input.getText().split("\\,");
            int lengthValues = values.length;
            float array[] = new float[lengthValues];
            StringBuilder resultado = new StringBuilder();

            pantallaResultado.setText("Valores ingresados: [  ");
            for (int i = 0; i < lengthValues; i++) {
                array[i] = Float.parseFloat(values[i]);
                resultado.append(values[i]);
                resultado.append(",");
            }
            resultado.deleteCharAt(resultado.length() - 1);
            pantallaResultado.append(resultado.toString());
            pantallaResultado.append("  ]");

            final Operaciones calculadora = new Operaciones(array);
            pantallaResultado.append("\nSuma = " + calculadora.suma());
            pantallaResultado.append("\nMultiplicación = " + calculadora.multiplicacion());
            pantallaResultado.append("\nResta = " + calculadora.resta());
            if (array[0] != 0) {
                pantallaResultado.append("\nDivisión = " + calculadora.limitarDecimal(calculadora.division()));
            } else {
                pantallaResultado.append("\nDivisión = No se puede dividir entre cero");
            }
        }

    }//GEN-LAST:event_realizarOperacionActionPerformed

    private void InterfazPromedioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InterfazPromedioActionPerformed
        final interfazNota abrir = new interfazNota();
        abrir.setVisible(true);
    }//GEN-LAST:event_InterfazPromedioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(interfazInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(interfazInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(interfazInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(interfazInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new interfazInicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem InterfazPromedio;
    private javax.swing.JMenu extra;
    private javax.swing.JTextField input;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea pantallaResultado;
    private javax.swing.JButton realizarOperacion;
    // End of variables declaration//GEN-END:variables
}
